### ISSUE TITLE
Arduino DUE pin mapping

### ISSUE THREAD

**Issue by NachtRaveVL** [antodom/pwm_lib#1]
I was very curious about what the actual board pin assignments were for the Arduino DUE, since they are not listed in the pwn_defs.h file, so in case you wanted to know:

```
enum class pwm_pin: uint32_t
    {
      // PWM pins listed on Table 38-2 for Atmel ATSAM3X8E 
      // datasheet available in www.atmel.com
      // NOTE: only it is possible to use one pin for each
      // PWM channel 
      PWMH0_PA8 , // PWM_CH0 -> RX0
      PWMH0_PB12, // PWM_CH0 -> SDA (SDA0)
      PWMH0_PC3 , // PWM_CH0 -> D35
      PWML0_PA21, // PWM_CH0 -> LED TX (?D13?)
      PWML0_PB16, // PWM_CH0 -> DAC1 (audio)
      PWML0_PC2 , // PWM_CH0 -> D34

      PWMH1_PA19, // PWM_CH1 -> D42
      PWMH1_PB13, // PWM_CH1 -> SCL (SCL0)
      PWMH1_PC5 , // PWM_CH1 -> D37
      PWML1_PA12, // PWM_CH1 -> RX2
      PWML1_PB17, // PWM_CH1 -> AI8
      PWML1_PC4 , // PWM_CH1 -> D36

      PWMH2_PA13, // PWM_CH2 -> TX2
      PWMH2_PB14, // PWM_CH2 -> D53 (SPISS)
      PWMH2_PC7 , // PWM_CH2 -> D39
      PWML2_PA20, // PWM_CH2 -> D43
      PWML2_PB18, // PWM_CH2 -> AI9
      PWML2_PC6 , // PWM_CH2 -> D38

      PWMH3_PA9 , // PWM_CH3 -> TX0
      PWMH3_PB15, // PWM_CH3 -> DAC0 (audio)
      PWMH3_PC9 , // PWM_CH3 -> D41
      PWML3_PA0 , // PWM_CH3 -> CANTX
      PWML3_PB19, // PWM_CH3 -> AI10
      PWML3_PC8 , // PWM_CH3 -> D40

      PWMH4_PC20, // PWM_CH4 -> na
      PWML4_PC21, // PWM_CH4 -> D9 (PWN)

      PWMH5_PC19, // PWM_CH5 -> D44
      PWML5_PC22, // PWM_CH5 -> D8 (PWN)

      PWMH6_PC18, // PWM_CH6 -> D45
      PWML6_PC23, // PWM_CH6 -> D7 (PWN)

      PWML7_PC24  // PWM_CH7 -> D6 (PWN)
    };
```

It is interesting to note that D6, D7, D8, and D9 are the ones for the DUE that are most likely most important for changing PWN output frequency (just be careful about D44 and D45). I am unsure how setting the other channels, CH0 through CH3, would interact with a live system, as it may cause a host of other issues.

I referenced these pin mappings from here: https://www.arduino.cc/en/Hacking/PinMappingSAM3X - however, I am unsure of what PC20 goes to (possibly internal?), and for LED TX I am curious if it refers to D13 but again am unsure. Also the DAC0 and DAC1 lines are actually for the onboard DUE Audio library for analog output of WAV files, and I am again unsure how those would be affected.

Finally, props to the author for writing this library. Greetings from Seattle. =)

Hope this helps!

**Comment by antodom** [comment]
Hi there Johanna,

Thanks for collecting the pin mapping information. I though that having the link on the README.md was enough, but it is really a good idea to post the mapping here.
