### ISSUE TITLE
Max PWM frequency on Arduino Due ?

### ISSUE THREAD

**Issue by GiacomoDBi** [antodom/pwm_lib#3]
Hi Antonio,
just a question (I didn't find your contact info..): I saw you report examples with "low freq" PWM. I'm searching a PWM library for the Arduino Due able to run with PWM frequencies around 40-80kHz. May I use pwm_lib for my project?
thank you vary much,
Giacomo

**Comment by antodom** [comment]
Hi there GiacomiDBi,

I would say that you should not have any problems to get to this "high" frequencies with pwm_lib of 40-80 kHz.

I hope it helps.
