### ISSUE TITLE
Library uncompilable with newer GCC versions

### ISSUE THREAD

**Issue by maxgerhardt** [antodom/pwm_lib#5]
When using PlatformIO with the library and the basic example sketch, a compilation error occurs.

`platformio.ini`: 

```
[env:due]
platform = atmelsam
board = due 
framework = arduino
lib_deps = 
	https://github.com/antodom/tc_lib.git
	https://github.com/antodom/pwm_lib.git
```

`src\main.cpp`: From https://github.com/antodom/pwm_lib/blob/master/examples/basic_test/basic_test.ino

Error: 

```
In file included from lib/pwm_lib/pwm_lib.h:37:0,
                 from src/main.cpp:36:
/home/ian/.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam3xa/include/sam3x8e.h:494:21: error: 'reinterpret_cast<Pio*>(1074662912)' is not a constant expression
 #define PIOA       ((Pio    *)0x400E0E00U) /**< \brief (PIOA      ) Base Address */
                    ~^~~~~~~~~~~~~~~~~~~~~~
lib/pwm_lib/pwm_defs.h:98:37: note: in definition of macro 'pin_traits_specialization'
       static constexpr Pio* pio_p = pio; \
                                     ^~~
lib/pwm_lib/pwm_defs.h:109:52: note: in expansion of macro 'PIOA'
     pin_traits_specialization(pwm_pin::PWMH0_PA8 , PIOA, PIO_PA8B_PWMH0 , ID_PIOA, PIO_PERIPH_B, PIO_DEFAULT,  PWM_CH0,   false  );
                                                    ^~~~
```

As it was found out in https://community.platformio.org/t/problem-with-arduino-pwm-lib/12930, this error is due to the lines 

https://github.com/antodom/pwm_lib/blob/168cc25e23cef14258988acde926617b2abb86ed/pwm_defs.h#L93-L109

With e.g.

```cpp
static constexpr Pio* pio_p = PIOA;
```

and 

```
#define PIOA       ((Pio    *)0x400E0E00U) /**< \brief (PIOA      ) Base Address */
``` 

not being seen as `constexpr` with newer compiler version. PlatformIO uses GCC version 7.2.1 by default, which throws the above compilation error. 

Arduino IDE uses the ancient 4.8.3-2014q1 compiler version for which this is no constant cast error. When forcing this compiler version in `platformio.ini` by using 

```
platform_packages = 
	toolchain-gccarmnoneeabi @ https://bintray.com/platformio/dl-packages/download_file?file_path=toolchain-gccarmnoneeabi-windows-1.40804.0.tar.gz
```

The project compiles succesfully. Can the code be written to be compilable with newer GCC versions to be robust in case Arduino IDE updates its compiler version (and to work in PIO without workarounds)?

**Comment by antodom** [comment]
Hi there @maxgerhardt,

Thanks for you comment.

Certainly this line:

  static constexpr Pio* pio_p = PIOA;

is no more accepted in tha last C++ standards, so in last compiler versions. C++ const expressions can not be initialized with a reinterpret_cast<> anymore. Well, I have modified the library for fixing this problem. If you can, please, check and tell me if the problems is solved.

And thanks for using pwm_lib.
Best.
