### ISSUE TITLE
Will this library influence the function of other pins?

### ISSUE THREAD

**Issue by BrainZhang07** [antodom/pwm_lib#7]
Hi,

I tried your library and it is great. I was able to create stable PWM signals with different frenquency. 

However, I would like to know, after I declare one pin of a PWM channel, will the function of the other pins be influenced? For example, if I use PWML1_PB17, // PWM_CH1	//Analog In 8 as the PWM pin, can I use the other pins of PWM_CH1 or other channels as normal digital pins and analogy pins and use functions like digitalwrite and digitalread?
I have this question because I found I can read the same period I set for  PWML1_PB17 from PWML2_PB18. All though I did not declare PWML2_PB18 at all, which migh be the problem.

And would the functions of delay(), mills(), interupt be influenced?(same questions for tc_lib)

Best Regards,
Brian

**Comment by antodom** [comment]
Hi there,

Pins used for PWM functionality are independent each other, its use as PWM output signals does not have any influence on the rest of pins. As to if pwm_lib does have any influence or conflict with delay() and millis(), I don't think so. Respect to tc_lib, it will depend on the TC module, if any, that millis() and delays() use. If this is the case, you should avoid using it with tc_lib. In section 6. Incompatibilities in pwm_lib and tc_lib you have more info about that.

I hope it helps.
