### ISSUE TITLE
Inverted PWM?

### ISSUE THREAD

**Issue by erdavci** [antodom/pwm_lib#8]
In some cases we need an inverted PWM signal. How can we do this? Or better yet, can a function be added to the existing library to invert the PWM signal? (Like as PWM.start(period, duty, inverted = true [default: false])
Best Regards.

**Comment by antodom** [comment]
Hi there @erdavci,

Sorry for the delay in my answer, but I have been very busy in the last weeks. Following your suggestion, I have modified function member start() for accepting a third flag argument to indicate that the output is inverted, which is false by default.

Please, update pwm_lib,  test it and tell me if it works correctly. 
I hope it helps.

**Comment by erdavci** [comment]
![03_f](https://user-images.githubusercontent.com/84367232/179655690-10ae2d68-ad97-43cc-9200-c83b8cb3e89d.png)
I quickly tested it. It works perfectly. Thank you very much d^_^b
